/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Survey } from "./Survey";
import { SurveyCountArgs } from "./SurveyCountArgs";
import { SurveyFindManyArgs } from "./SurveyFindManyArgs";
import { SurveyFindUniqueArgs } from "./SurveyFindUniqueArgs";
import { CreateSurveyArgs } from "./CreateSurveyArgs";
import { UpdateSurveyArgs } from "./UpdateSurveyArgs";
import { DeleteSurveyArgs } from "./DeleteSurveyArgs";
import { User } from "../../user/base/User";
import { SurveyService } from "../survey.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Survey)
export class SurveyResolverBase {
  constructor(
    protected readonly service: SurveyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Survey",
    action: "read",
    possession: "any",
  })
  async _surveysMeta(
    @graphql.Args() args: SurveyCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Survey])
  @nestAccessControl.UseRoles({
    resource: "Survey",
    action: "read",
    possession: "any",
  })
  async surveys(@graphql.Args() args: SurveyFindManyArgs): Promise<Survey[]> {
    return this.service.surveys(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Survey, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Survey",
    action: "read",
    possession: "own",
  })
  async survey(
    @graphql.Args() args: SurveyFindUniqueArgs
  ): Promise<Survey | null> {
    const result = await this.service.survey(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Survey)
  @nestAccessControl.UseRoles({
    resource: "Survey",
    action: "create",
    possession: "any",
  })
  async createSurvey(@graphql.Args() args: CreateSurveyArgs): Promise<Survey> {
    return await this.service.createSurvey({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Survey)
  @nestAccessControl.UseRoles({
    resource: "Survey",
    action: "update",
    possession: "any",
  })
  async updateSurvey(
    @graphql.Args() args: UpdateSurveyArgs
  ): Promise<Survey | null> {
    try {
      return await this.service.updateSurvey({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Survey)
  @nestAccessControl.UseRoles({
    resource: "Survey",
    action: "delete",
    possession: "any",
  })
  async deleteSurvey(
    @graphql.Args() args: DeleteSurveyArgs
  ): Promise<Survey | null> {
    try {
      return await this.service.deleteSurvey(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Survey): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
